#!/usr/bin/with-contenv sh
# shellcheck shell=sh

export PUID=${PUID:-1000}
export PGID=${PGID:-1000}

export TZ=${TZ:-UTC}

export MEMORY_LIMIT=${MEMORY_LIMIT:-256M}
export CLEAR_ENV=${CLEAR_ENV:-yes}
export MAX_FILE_UPLOADS=${MAX_FILE_UPLOADS:-50}
export OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE:-128}
export UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-16M}

export REAL_IP_FROM=${REAL_IP_FROM:-0.0.0.0/32}
export REAL_IP_HEADER=${REAL_IP_HEADER:-X-Forwarded-For}
export LOG_IP_VAR=${LOG_IP_VAR:-remote_addr}
export AUTH_DELAY=${AUTH_DELAY:-0s}
export NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-2}
export NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
export LOG_ACCESS=${LOG_ACCESS:-true}

export XMLRPC_AUTHBASIC_STRING=${XMLRPC_AUTHBASIC_STRING:-rTorrent XMLRPC restricted access}
export RUTORRENT_AUTHBASIC_STRING=${RUTORRENT_AUTHBASIC_STRING:-ruTorrent restricted access}
export XMLRPC_PORT=${XMLRPC_PORT:-8000}
export XMLRPC_HEALTH_PORT=$((XMLRPC_PORT + 1))
export XMLRPC_SIZE_LIMIT=${XMLRPC_SIZE_LIMIT:-4M}

export RUTORRENT_PORT=${RUTORRENT_PORT:-8080}
export RUTORRENT_HEALTH_PORT=$((RUTORRENT_PORT + 1))

export RT_DEFAULT_DIR=${RT_DEFAULT_DIR:-/downloads}
export RT_LOG_LEVEL=${RT_LOG_LEVEL:-info}
export RT_LOG_EXECUTE=${RT_LOG_EXECUTE:-false}
export RT_LOG_XMLRPC=${RT_LOG_XMLRPC:-false}
export RT_SESSION_SAVE_SECONDS=${RT_SESSION_SAVE_SECONDS:-3600}
export RT_TRACKER_DELAY_SCRAPE=${RT_TRACKER_DELAY_SCRAPE:-true}
export RT_SEND_BUFFER_SIZE=${RT_SEND_BUFFER_SIZE:-4M}
export RT_RECEIVE_BUFFER_SIZE=${RT_RECEIVE_BUFFER_SIZE:-4M}
export RT_PREALLOCATE_TYPE=${RT_PREALLOCATE_TYPE:-0}

export RU_REMOVE_CORE_PLUGINS=${RU_REMOVE_CORE_PLUGINS:-false}
export RU_HTTP_USER_AGENT=${RU_HTTP_USER_AGENT:-$(php -r 'include "/var/www/rutorrent/conf/config.php"; echo $httpUserAgent;')}
export RU_HTTP_TIME_OUT=${RU_HTTP_TIME_OUT:-30}
export RU_HTTP_USE_GZIP=${RU_HTTP_USE_GZIP:-true}
export RU_RPC_TIME_OUT=${RU_RPC_TIME_OUT:-5}
export RU_LOG_RPC_CALLS=${RU_LOG_RPC_CALLS:-false}
export RU_LOG_RPC_FAULTS=${RU_LOG_RPC_FAULTS:-true}
export RU_PHP_USE_GZIP=${RU_PHP_USE_GZIP:-false}
export RU_PHP_GZIP_LEVEL=${RU_PHP_GZIP_LEVEL:-2}
export RU_SCHEDULE_RAND=${RU_SCHEDULE_RAND:-10}
export RU_LOG_FILE=${RU_LOG_FILE:-/data/rutorrent/rutorrent.log}
export RU_DO_DIAGNOSTIC=${RU_DO_DIAGNOSTIC:-true}
export RU_CACHED_PLUGIN_LOADING=${RU_CACHED_PLUGIN_LOADING:-false}
export RU_SAVE_UPLOADED_TORRENTS=${RU_SAVE_UPLOADED_TORRENTS:-true}
export RU_OVERWRITE_UPLOADED_TORRENTS=${RU_OVERWRITE_UPLOADED_TORRENTS:-false}
export RU_FORBID_USER_SETTINGS=${RU_FORBID_USER_SETTINGS:-false}
export RU_LOCALE=${RU_LOCALE:-UTF8}

export RT_DHT_PORT=${RT_DHT_PORT:-6881}
export RT_INC_PORT=${RT_INC_PORT:-50000}

/etc/s6-overlay/s6-rc.d/init-config/00-timezone.sh
/etc/s6-overlay/s6-rc.d/init-config/01-logo.sh
/etc/s6-overlay/s6-rc.d/init-config/02-user.sh
/etc/s6-overlay/s6-rc.d/init-config/03-folders.sh
/etc/s6-overlay/s6-rc.d/init-config/04-php.sh
/etc/s6-overlay/s6-rc.d/init-config/05-nginx.sh
/etc/s6-overlay/s6-rc.d/init-config/06-config.sh