#!/usr/bin/with-contenv sh
# shellcheck shell=sh

/etc/s6-overlay/s6-rc.d/init-config/01-logo.sh
/etc/s6-overlay/s6-rc.d/init-config/02-init-user.sh
/etc/s6-overlay/s6-rc.d/init-config/03-init-folders.sh
/etc/s6-overlay/s6-rc.d/init-config/04-init-config.sh