name: drrako-rtorrent

services:
  dockerized-rtorrent:
    image: ${DOCKERIZED_RTORRENT_IMAGE:-drrako/rtorrent}
    container_name: ${DOCKERIZED_RTORRENT_CONTAINER:-drrako-rtorrent}
    networks:
      - dockerized-rtorrent
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent.env"
      - ".env"
    volumes:
      - "./data:/data"
      - "./downloads:/media/downloads"
      - "./passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

networks:
  dockerized-rtorrent:
    name: dockerized-rtorrent
