#!/usr/bin/with-contenv sh
# shellcheck shell=sh

echo "-----------------------------------------------------------------------------------------";
echo "  ____             _             _             _       _____                         _   ";
echo " |  _ \  ___   ___| | _____ _ __(_)_______  __| |  _ _|_   _|__  _ __ _ __ ___ _ __ | |_ ";
echo " | | | |/ _ \ / __| |/ / _ \ '__| |_  / _ \/ _\` | | '__|| |/ _ \| '__| '__/ _ \ '_ \| __|";
echo " | |_| | (_) | (__|   <  __/ |  | |/ /  __/ (_| | | |   | | (_) | |  | | |  __/ | | | |_ ";
echo " |____/ \___/ \___|_|\_\___|_|  |_/___\___|\__,_| |_|   |_|\___/|_|  |_|  \___|_| |_|\__|";
echo "                                                                                         ";


echo "                        https://github.com/drrako/dockerized-rtorrent                    ";
echo "-----------------------------------------------------------------------------------------";

PUID=${PUID:-1000}
PGID=${PGID:-1000}

echo "Creating rtorrent user with PUID [$PUID] and PGID [$PGID].."
addgroup -g $PGID rtorrent
adduser -D -H -u $PUID -G rtorrent -s /bin/sh rtorrent